version = 1

[[analyzers]]
name = "shell"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["angular"]
  environment = ["nodejs"]

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"